# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    reviewers:
      - "Sassiest01"
      - "willsawyerrrr"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    reviewers:
      - "Sassiest01"
      - "willsawyerrrr"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    reviewers:
      - "Sassiest01"
      - "willsawyerrrr"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
