name: Publish to PyPI

on:
  push:
    branches: main

permissions:
  contents: read

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      is-greater: ${{ steps.check-version.outputs.local_version_is_higher }}
    steps:
      - uses: actions/checkout@v4

      - id: check-version
        uses: maybe-hello-world/pyproject-check-version@v4

  publish:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/entegywrapper
    if: ${{ fromJson(needs.check-version.outputs.is-greater) }}
    needs: check-version
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - run: poetry install
      - run: poetry build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.8.14
